name: CI

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ add-linter-target ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: amd64/gcc:latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello world
        run: echo "hello world"
      # - name: Lint
      #   run: ./linter.sh
      # - name: Build
      #   run: |
      #     cd build
      #     make
      # - name: Unit Tests
      #   run: |
      #     cd build
      #     ./CitrusTests
      # - name: Check Memory Management
      #   run: |
      #     cd build
      #     chmod 700 ./libCitrus.a
      #     valgrind ./libCitrus.a
      